# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-24 18:30
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LawPP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_year', models.IntegerField(verbose_name='A\xf1o de publicacion')),
                ('name', models.TextField(verbose_name='Nombre')),
                ('file_law', models.FileField(blank=True, null=True, upload_to='law_pp', verbose_name='Archivo de Ley')),
                ('summary', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido')),
            ],
            options={
                'verbose_name': 'Ley Reglamentaria del Presupuesto Participativo',
                'verbose_name_plural': 'Leyes Reglamentarias del Presupuesto Participativo',
            },
        ),
        migrations.CreateModel(
            name='PeriodPP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='A\xf1o')),
                ('is_public', models.BooleanField(default=False, verbose_name='Es Publico')),
                ('pdf_iecm', models.FileField(blank=True, null=True, upload_to='period_pp', verbose_name='Archivo PDF del IECM')),
                ('global_error_stack', models.TextField(blank=True, null=True)),
                ('all_results', models.TextField(blank=True, null=True)),
                ('logo', models.CharField(blank=True, default='gobierno de la ciudad de mexico; ciudad de mexico', max_length=100, null=True)),
                ('unidad', models.CharField(blank=True, default='unidad responsable del gasto', max_length=100, null=True)),
                ('title', models.CharField(blank=True, default='cuenta publica de la ciudad de mexico', max_length=100, null=True)),
                ('ppd', models.CharField(blank=True, default='ppd presupuesto participativo para las delegaciones', max_length=100, null=True)),
                ('ammounts', models.CharField(blank=True, default='presupuesto (pesos con dos decimales', max_length=100, null=True)),
                ('colonia', models.CharField(blank=True, default='colonia o pueblo originario', max_length=100, null=True)),
                ('proyecto', models.CharField(blank=True, default='proyecto', max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, default='descripci\xf3n', max_length=100, null=True)),
                ('avance', models.CharField(blank=True, default='avance del proyecto; del proyecto', max_length=100, null=True)),
                ('aprobado', models.CharField(blank=True, default='aprobado', max_length=100, null=True)),
                ('modificado', models.CharField(blank=True, default='modificado', max_length=100, null=True)),
                ('ejercido', models.CharField(blank=True, default='ejercido', max_length=100, null=True)),
                ('variacion', models.CharField(blank=True, default='variaci\xf3n', max_length=100, null=True)),
                ('law_pp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='period.LawPP', verbose_name='Ley Reglamentaria del PP')),
            ],
            options={
                'verbose_name': 'Periodo de Presupuesto Participativo',
                'verbose_name_plural': 'Periodos de Presupuesto Participativo',
            },
        ),
    ]
