# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-07-13 23:55
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LawPP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_year', models.IntegerField()),
                ('name', models.TextField()),
                ('file_law', models.FileField(blank=True, null=True, upload_to='law_pp')),
                ('summary', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ley Reglamentaria del Presupuesto Participativo',
                'verbose_name_plural': 'Leyes Reglamentarias del Presupuesto Participativo',
            },
        ),
        migrations.CreateModel(
            name='PeriodPP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('is_public', models.BooleanField(default=False)),
                ('excel_iedf', models.FileField(upload_to='period_pp')),
                ('law_pp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='period.LawPP')),
            ],
            options={
                'verbose_name': 'Periodo de Presupuesto Participativo',
                'verbose_name_plural': 'Periodos de Presupuesto Participativo',
            },
        ),
    ]
