# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-07-14 17:48
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('period', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodpp',
            name='excel_iedf',
        ),
        migrations.AddField(
            model_name='periodpp',
            name='pdf_iedf',
            field=models.FileField(blank=True, null=True, upload_to='period_pp', verbose_name='Archivo PDF del IEDF'),
        ),
        migrations.AlterField(
            model_name='lawpp',
            name='file_law',
            field=models.FileField(blank=True, null=True, upload_to='law_pp', verbose_name='Archivo de Ley'),
        ),
        migrations.AlterField(
            model_name='lawpp',
            name='name',
            field=models.TextField(verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='lawpp',
            name='publish_year',
            field=models.IntegerField(verbose_name='A\xf1o de publicacion'),
        ),
        migrations.AlterField(
            model_name='lawpp',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='periodpp',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Es Publico'),
        ),
        migrations.AlterField(
            model_name='periodpp',
            name='law_pp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='period.LawPP', verbose_name='Ley Reglamentaria del PP'),
        ),
        migrations.AlterField(
            model_name='periodpp',
            name='year',
            field=models.IntegerField(verbose_name='A\xf1o'),
        ),
    ]
