# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-11-20 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('period', '0004_auto_20200715_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodpp',
            name='ammounts',
            field=models.CharField(blank=True, default='presupuesto (pesos con dos decimales', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='periodpp',
            name='aprobado',
            field=models.CharField(blank=True, default='aprobado', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='periodpp',
            name='avance',
            field=models.CharField(blank=True, default='avance del proyecto; del proyecto', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='periodpp',
            name='colonia',
            field=models.CharField(blank=True, default='colonia o pueblo originario', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='periodpp',
            name='descripcion',
            field=models.CharField(blank=True, default='descripci\xf3n', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='periodpp',
            name='ejercido',
            field=models.CharField(blank=True, default='ejercido', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='periodpp',
            name='logo',
            field=models.CharField(blank=True, default='gobierno de la ciudad de mexico; ciudad de mexico', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='periodpp',
            name='modificado',
            field=models.CharField(blank=True, default='modificado', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='periodpp',
            name='ppd',
            field=models.CharField(blank=True, default='ppd presupuesto participativo para las delegaciones', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='periodpp',
            name='proyecto',
            field=models.CharField(blank=True, default='proyecto', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='periodpp',
            name='title',
            field=models.CharField(blank=True, default='cuenta publica de la ciudad de mexico', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='periodpp',
            name='unidad',
            field=models.CharField(blank=True, default='unidad responsable del gasto', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='periodpp',
            name='variacion',
            field=models.CharField(blank=True, default='variaci\xf3n', max_length=100, null=True),
        ),
    ]
