# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-11-26 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('period', '0005_auto_20201119_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodpp',
            name='all_results',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodpp',
            name='global_error_stack',
            field=models.TextField(blank=True, null=True),
        ),
    ]
