# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-07-13 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryIEDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('year_start', models.IntegerField()),
                ('year_end', models.IntegerField()),
            ],
            options={
                'verbose_name': 'CategoryIEDF',
                'verbose_name_plural': 'Categories IEDF',
            },
        ),
    ]
