# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-07-14 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryiedf',
            options={'verbose_name': 'Categoria IEDF', 'verbose_name_plural': 'Categorias IEDF'},
        ),
        migrations.AlterField(
            model_name='categoryiedf',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='categoryiedf',
            name='year_end',
            field=models.IntegerField(verbose_name='A\xf1o de Fin'),
        ),
        migrations.AlterField(
            model_name='categoryiedf',
            name='year_start',
            field=models.IntegerField(verbose_name='A\xf1o de Inicio'),
        ),
    ]
