# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-01 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOllin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('public_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('icon', models.CharField(blank=True, max_length=30, null=True)),
                ('develop_community', models.BooleanField(default=False)),
                ('dictionary_values', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CategoryOllin',
                'verbose_name_plural': 'CategoryOllins',
            },
        ),
    ]
