# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-07-15 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_auto_20200714_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryiedf',
            name='year_end',
            field=models.IntegerField(blank=True, null=True, verbose_name='A\xf1o de Fin'),
        ),
        migrations.AlterField(
            model_name='categoryiedf',
            name='year_start',
            field=models.IntegerField(blank=True, null=True, verbose_name='A\xf1o de Inicio'),
        ),
    ]
