# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-07-16 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0004_auto_20200715_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripci\xf3n')),
                ('rules', models.TextField(blank=True, null=True, verbose_name='Reglas')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Anomal\xeda',
                'verbose_name_plural': 'Anomal\xedas',
            },
        ),
    ]
