# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-08-16 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0005_anomaly'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryiecm',
            name='color',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='categoryiecm',
            name='icon',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='\xcdcono'),
        ),
    ]
