# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-11-14 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0006_auto_20200816_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
