# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-24 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geographic', '0001_initial'),
        ('period', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('json_variables', models.TextField(blank=True, null=True)),
                ('headers', models.TextField(blank=True, null=True)),
                ('table_data', models.TextField(blank=True, null=True)),
                ('first_headers_used', models.BooleanField(default=True)),
                ('vision_data', models.TextField(blank=True, null=True)),
                ('clean_data', models.TextField(blank=True, null=True)),
                ('error_cell', models.TextField(blank=True, null=True, verbose_name='pila de errores')),
                ('len_array_numbers', models.CharField(blank=True, max_length=80, null=True)),
                ('data_row_numbers', models.TextField(blank=True, null=True, verbose_name='Datos de columnas num\xe9ricas')),
                ('data_row_suburbs', models.TextField(blank=True, null=True, verbose_name='Datos de columna de suburbs')),
                ('status', models.CharField(blank=True, default='uncleaned', max_length=80, null=True)),
                ('need_manual_ref', models.NullBooleanField()),
                ('manual_ref', models.TextField(blank=True, null=True)),
                ('need_second_manual_ref', models.NullBooleanField()),
                ('validated', models.NullBooleanField()),
                ('table_ref', models.TextField(blank=True, null=True, verbose_name='Referencia de filas')),
                ('table_ref_columns', models.TextField(blank=True, null=True, verbose_name='Referencias de Columnas')),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublicAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variables', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='uncleaned', max_length=80, null=True)),
                ('error_cell', models.TextField(blank=True, null=True, verbose_name='pila de errores')),
                ('orphan_rows', models.TextField(blank=True, null=True, verbose_name='Filas no insertadas')),
                ('approved', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Aprobado')),
                ('assigned', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Asignado')),
                ('modified', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Modificado')),
                ('executed', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ejecutado')),
                ('vertical_align_ammounts', models.CharField(blank=True, choices=[('top', 'top'), ('center', 'center'), ('bottom', 'bottom')], max_length=50, null=True)),
                ('unreadable', models.CharField(blank=True, choices=[('bajo', 'bajo'), ('media', 'media'), ('alto', 'alto')], max_length=50, null=True, verbose_name='Nivel de ilegibilidad')),
                ('ignore_columns', models.CharField(blank=True, help_text='columnas a ignorar para la alineacion horizontal (4-8)', max_length=50, null=True)),
                ('approved_mean', models.FloatField(blank=True, null=True)),
                ('executed_mean', models.FloatField(blank=True, null=True)),
                ('not_executed', models.IntegerField(blank=True, null=True)),
                ('minus_10', models.IntegerField(blank=True, null=True)),
                ('minus_5', models.IntegerField(blank=True, null=True)),
                ('similar', models.IntegerField(blank=True, null=True)),
                ('plus_5', models.IntegerField(blank=True, null=True)),
                ('no_info', models.NullBooleanField()),
                ('match_review', models.NullBooleanField()),
                ('suburb_count', models.IntegerField(blank=True, null=True)),
                ('manual_mach', models.TextField(blank=True, null=True)),
                ('comment_match', models.TextField(blank=True, null=True)),
                ('period_pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='period.PeriodPP', verbose_name='Periodo PP')),
                ('townhall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geographic.TownHall', verbose_name='Alcald\xeda')),
            ],
            options={
                'verbose_name': 'Cuenta Publica',
                'verbose_name_plural': 'Cuentas Publicas',
            },
        ),
        migrations.AddField(
            model_name='ppimage',
            name='public_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pp_images', to='public_account.PublicAccount'),
        ),
    ]
