# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-25 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0002_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='vision_blocks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='row',
            name='vision_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
