# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-08-21 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0003_auto_20200812_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppimage',
            name='number_of_rows',
            field=models.TextField(blank=True, null=True),
        ),
    ]
