# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-26 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0003_auto_20210525_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='row',
            name='variation_calc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
