# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-27 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0004_auto_20210526_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ppimage',
            options={'verbose_name': 'Imagen de Cuenta Publica', 'verbose_name_plural': 'Imagenes de Cuentas Publicas'},
        ),
    ]
