# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-08-21 01:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0004_ppimage_number_of_rows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ppimage',
            old_name='number_of_rows',
            new_name='data_row_numbers',
        ),
    ]
