# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-31 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0005_auto_20210526_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOllin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('public_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('icon', models.CharField(blank=True, max_length=30, null=True)),
                ('develop_community', models.BooleanField(default=False)),
                ('dictionary_values', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CategoryOllin',
                'verbose_name_plural': 'CategoryOllins',
            },
        ),
        migrations.CreateModel(
            name='RowCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_account.CategoryOllin')),
            ],
            options={
                'verbose_name': 'RowCategory',
                'verbose_name_plural': 'RowCategorys',
            },
        ),
        migrations.AlterField(
            model_name='row',
            name='final_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='project.FinalProject'),
        ),
        migrations.AddField(
            model_name='rowcategory',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_account.Row'),
        ),
        migrations.AddField(
            model_name='row',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='public_account.CategoryOllin'),
        ),
    ]
