# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-08-21 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0005_auto_20200820_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppimage',
            name='status',
            field=models.CharField(blank=True, default='uncleaned', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='publicaccount',
            name='status',
            field=models.CharField(blank=True, default='uncleaned', max_length=80, null=True),
        ),
    ]
