# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-01 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_categoryollin'),
        ('public_account', '0008_auto_20210531_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='row',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classification.CategoryOllin'),
        ),
        migrations.AddField(
            model_name='rowcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classification.CategoryOllin'),
        ),
    ]
