# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-08-31 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0008_ppimage_error_cell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ppimage',
            name='rows_count',
        ),
        migrations.AddField(
            model_name='ppimage',
            name='data_row_suburbs',
            field=models.TextField(blank=True, null=True, verbose_name='Datos de columna de suburbs'),
        ),
        migrations.AddField(
            model_name='ppimage',
            name='len_array_numbers',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='ppimage',
            name='data_row_numbers',
            field=models.TextField(blank=True, null=True, verbose_name='Datos de columnas num\xe9ricas'),
        ),
    ]
