# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-08-31 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0009_auto_20200830_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaccount',
            name='error_cell',
            field=models.TextField(blank=True, null=True, verbose_name='pila de errores'),
        ),
        migrations.AlterField(
            model_name='publicaccount',
            name='townhall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geographic.TownHall', verbose_name='Alcald\xeda'),
        ),
    ]
