# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-01 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0009_auto_20210531_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowcategory',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atl_categories', to='public_account.Row'),
        ),
    ]
