# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-08-31 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0010_auto_20200831_0023'),
        ('public_account', '0009_ppimage_vision_data'),
    ]

    operations = [
    ]
