# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-14 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0010_auto_20210601_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaccount',
            name='not_approved',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicaccount',
            name='not_reported',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
