# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-09-03 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0011_merge_20200831_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaccount',
            name='approved',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Aprobado'),
        ),
        migrations.AddField(
            model_name='publicaccount',
            name='executed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ejecutado'),
        ),
        migrations.AddField(
            model_name='publicaccount',
            name='modified',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Modificado'),
        ),
        migrations.AddField(
            model_name='publicaccount',
            name='vertical_align_ammounts',
            field=models.CharField(blank=True, choices=[('top', 'top'), ('center', 'center'), ('bottom', 'bottom')], max_length=50, null=True),
        ),
    ]
