# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-11-17 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0012_auto_20200903_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaccount',
            name='orphan_rows',
            field=models.TextField(blank=True, null=True, verbose_name='Filas no insertadas'),
        ),
    ]
