# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-16 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0012_auto_20210614_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaccount',
            name='approved_median',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
