# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-04 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0015_auto_20201125_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppimage',
            name='manual_ref',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ppimage',
            name='need_manual_ref',
            field=models.NullBooleanField(),
        ),
    ]
