# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-11 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0016_auto_20210204_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaccount',
            name='assigned_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicaccount',
            name='executed_mean',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
