# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-11 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0017_auto_20210211_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaccount',
            name='minus_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicaccount',
            name='minus_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicaccount',
            name='plus_10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicaccount',
            name='plus_5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicaccount',
            name='similar',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
