# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-11 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0018_auto_20210211_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaccount',
            name='not_executed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicaccount',
            name='minus_10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicaccount',
            name='minus_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicaccount',
            name='plus_10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicaccount',
            name='plus_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicaccount',
            name='similar',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
