# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-11 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0019_auto_20210211_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaccount',
            name='no_info',
            field=models.NullBooleanField(),
        ),
    ]
