# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-11 23:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0020_publicaccount_no_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicaccount',
            old_name='assigned_mean',
            new_name='approved_mean',
        ),
    ]
