# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-12 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0021_auto_20210211_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicaccount',
            name='plus_10',
        ),
    ]
