# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-16 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0022_remove_publicaccount_plus_10'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppimage',
            name='need_second_manual_ref',
            field=models.NullBooleanField(),
        ),
    ]
