# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-19 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0023_ppimage_need_second_manual_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaccount',
            name='match_review',
            field=models.NullBooleanField(),
        ),
    ]
