# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-19 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0026_ppimage_table_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaccount',
            name='assigned',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Asignado'),
        ),
    ]
