# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-19 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0027_publicaccount_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaccount',
            name='manual_mach',
            field=models.TextField(blank=True, null=True),
        ),
    ]
