# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-23 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0028_publicaccount_manual_mach'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaccount',
            name='comment_match',
            field=models.TextField(blank=True, null=True),
        ),
    ]
