# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-18 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0029_publicaccount_comment_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppimage',
            name='table_ref_columns',
            field=models.TextField(blank=True, null=True, verbose_name='Referencias de Columnas'),
        ),
        migrations.AlterField(
            model_name='ppimage',
            name='table_ref',
            field=models.TextField(blank=True, null=True, verbose_name='Referencia de filas'),
        ),
    ]
