# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-18 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0030_auto_20210518_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppimage',
            name='validated',
            field=models.NullBooleanField(),
        ),
    ]
