# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-18 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0031_ppimage_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='ppimage',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
