# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-19 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0032_ppimage_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppimage',
            name='public_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pp_images', to='public_account.PublicAccount'),
        ),
    ]
