# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-21 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_auto_20210521_1701'),
        ('public_account', '0033_auto_20210519_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('progress', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Avance del proyecto')),
                ('approved', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Aprobado')),
                ('modified', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Modificado')),
                ('executed', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ejecutado')),
                ('variation', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Variacion')),
                ('validated', models.NullBooleanField(verbose_name='Validado')),
                ('errors', models.TextField(blank=True, null=True)),
                ('sequential', models.SmallIntegerField(blank=True, null=True)),
                ('vision_data', models.TextField()),
                ('formatted_data', models.TextField(blank=True, null=True)),
                ('top', models.SmallIntegerField(blank=True, null=True)),
                ('bottom', models.SmallIntegerField(blank=True, null=True)),
                ('final_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.FinalProject')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public_account.PPImage')),
            ],
            options={
                'verbose_name': 'Row',
                'verbose_name_plural': 'Rows',
            },
        ),
    ]
