# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-07-14 00:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classification', '0001_initial'),
        ('period', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geographic', '0002_auto_20200713_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_cp', models.TextField(blank=True, null=True)),
                ('final_name', models.TextField(blank=True, null=True)),
                ('category_cp', models.CharField(blank=True, max_length=255, null=True)),
                ('total_votes', models.TextField(blank=True, null=True)),
                ('assigned', models.FloatField(blank=True, null=True)),
                ('approuved', models.FloatField(blank=True, null=True)),
                ('modified', models.FloatField(blank=True, null=True)),
                ('excecuted', models.FloatField(blank=True, null=True)),
                ('progress', models.IntegerField(blank=True, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('validated', models.BooleanField(default=False)),
                ('period_pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='period.PeriodPP')),
            ],
            options={
                'verbose_name': 'Proyecto Final en la Cuenta Publica',
                'verbose_name_plural': 'Proyectos Finales en la Cuenta Publica',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_iedf', models.CharField(max_length=255)),
                ('project_id', models.IntegerField()),
                ('votes', models.IntegerField(default=0)),
                ('is_winer', models.BooleanField(default=False)),
                ('category_iedf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classification.CategoryIEDF')),
                ('period_pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='period.PeriodPP')),
                ('suburb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geographic.Suburb')),
            ],
            options={
                'verbose_name': 'Proyecto de Presupuesto',
                'verbose_name_plural': 'Proyectos de Presupuestos',
            },
        ),
        migrations.AddField(
            model_name='finalproject',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
        migrations.AddField(
            model_name='finalproject',
            name='suburb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geographic.Suburb'),
        ),
        migrations.AddField(
            model_name='finalproject',
            name='user_validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
