# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-24 18:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geographic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classification', '0001_initial'),
        ('period', '0001_initial'),
        ('public_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyFinalProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification.Anomaly')),
            ],
            options={
                'verbose_name': 'Anomal\xeda y Proyecto Final',
                'verbose_name_plural': 'Anomal\xeda y Proyecto Final',
            },
        ),
        migrations.CreateModel(
            name='FinalProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_votes', models.IntegerField(blank=True, null=True, verbose_name='Total de Votos')),
                ('final_name', models.TextField(blank=True, null=True, verbose_name='Nombre Final')),
                ('description_cp', models.TextField(blank=True, null=True, verbose_name='Descripcion CP')),
                ('project_cp', models.CharField(blank=True, max_length=255, null=True, verbose_name='Proyecto CP')),
                ('assigned', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Asignado')),
                ('approved', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Aprobado')),
                ('modified', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Modificado')),
                ('executed', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ejecutado')),
                ('progress', models.FloatField(blank=True, null=True, verbose_name='Avance del proyecto')),
                ('variation', models.FloatField(blank=True, null=True, verbose_name='Variacion')),
                ('manual_capture', models.TextField(blank=True, null=True, verbose_name='Captura Manual')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('pre_clasification', models.TextField(blank=True, null=True, verbose_name='Pre-clasificaci\xf3n')),
                ('validated', models.NullBooleanField(verbose_name='Validado')),
                ('similar_suburb_name', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True, verbose_name='Nivel de similitud de nombre (-1 cuando es forzado)')),
                ('name_in_pa', models.CharField(blank=True, max_length=140, null=True, verbose_name='Nombre como aparece en cuenta p\xfablica')),
                ('json_variables', models.TextField(blank=True, null=True, verbose_name='Variables originales de su columna')),
                ('error_cell', models.TextField(blank=True, null=True, verbose_name='pila de errores')),
                ('inserted_data', models.BooleanField(default=False, verbose_name='Datos insertados desde cuenta p\xfablica')),
                ('data_raw', models.TextField(blank=True, null=True, verbose_name='Informacion de la imagen')),
                ('variation_calc', models.FloatField(blank=True, null=True)),
                ('range', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='public_account.PPImage')),
                ('period_pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='period.PeriodPP', verbose_name='Periodo PP')),
            ],
            options={
                'verbose_name': 'Proyecto Final en la Cuenta Publica',
                'verbose_name_plural': 'Proyectos Finales en la Cuenta Publica',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_iecm', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del IECM')),
                ('project_id', models.IntegerField(blank=True, null=True, verbose_name='ID del Proyecto')),
                ('votes_mro', models.IntegerField(default=0, verbose_name='Votos f\xedsicos')),
                ('votes_int', models.IntegerField(default=0, verbose_name='Votos internet')),
                ('votes', models.IntegerField(default=0, verbose_name='Votos')),
                ('is_winer', models.BooleanField(default=False, verbose_name='Es el ganador')),
                ('category_iecm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classification.CategoryIECM', verbose_name='Categoria IECM')),
                ('period_pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='period.PeriodPP', verbose_name='Periodo PP')),
                ('suburb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geographic.Suburb', verbose_name='Colonia')),
            ],
            options={
                'verbose_name': 'Proyecto de Presupuesto',
                'verbose_name_plural': 'Proyectos de Presupuestos',
            },
        ),
        migrations.AddField(
            model_name='finalproject',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Project', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='finalproject',
            name='suburb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geographic.Suburb', verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='finalproject',
            name='user_validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario validador'),
        ),
        migrations.AddField(
            model_name='anomalyfinalproject',
            name='final_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.FinalProject'),
        ),
        migrations.AddField(
            model_name='anomalyfinalproject',
            name='public_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='public_account.PublicAccount'),
        ),
    ]
