# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-26 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name_iecm',
            field=models.TextField(blank=True, null=True, verbose_name='Nombre del IECM'),
        ),
    ]
