# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-07-14 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalproject',
            name='total_votes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
