# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-26 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210526_1202'),
        ('project', '0002_auto_20210525_1156'),
    ]

    operations = [
    ]
