# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-02 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_merge_20210526_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='is_winer',
            new_name='is_winner',
        ),
    ]
