# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-07-15 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200714_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name_iedf',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del IEFD'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID del Proyecto'),
        ),
    ]
