# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-03 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20210601_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-votes'], 'verbose_name': 'Proyecto de Presupuesto', 'verbose_name_plural': 'Proyectos de Presupuestos'},
        ),
        migrations.AddField(
            model_name='finalproject',
            name='votes_int',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
