# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-07-15 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200715_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category_iedf',
            field=models.IntegerField(blank=True, null=True, verbose_name='Categoria IEDF'),
        ),
    ]
