# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-07-25 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_anomalyfinalproject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalproject',
            old_name='approuved',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='finalproject',
            old_name='excecuted',
            new_name='executed',
        ),
        migrations.RemoveField(
            model_name='finalproject',
            name='category_cp',
        ),
        migrations.AddField(
            model_name='finalproject',
            name='manual_capture',
            field=models.TextField(blank=True, null=True, verbose_name='Captura Manual'),
        ),
        migrations.AddField(
            model_name='finalproject',
            name='pre_clasification',
            field=models.TextField(blank=True, null=True, verbose_name='Pre-clasificaci\xf3n'),
        ),
        migrations.AddField(
            model_name='finalproject',
            name='project_cp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Proyecto CP'),
        ),
    ]
