# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-08-12 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_account', '0003_auto_20200812_1635'),
        ('project', '0010_auto_20200725_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalproject',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='public_account.PPImage'),
        ),
        migrations.AlterField(
            model_name='finalproject',
            name='approved',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Aprobado'),
        ),
        migrations.AlterField(
            model_name='finalproject',
            name='assigned',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Asignado'),
        ),
        migrations.AlterField(
            model_name='finalproject',
            name='executed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ejecutado'),
        ),
        migrations.AlterField(
            model_name='finalproject',
            name='modified',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Modificado'),
        ),
        migrations.AlterField(
            model_name='finalproject',
            name='progress',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Avance del proyecto'),
        ),
    ]
