# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-08-21 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_finalproject_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalproject',
            name='approved',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Aprobado'),
        ),
        migrations.AlterField(
            model_name='finalproject',
            name='assigned',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Asignado'),
        ),
        migrations.AlterField(
            model_name='finalproject',
            name='executed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ejecutado'),
        ),
        migrations.AlterField(
            model_name='finalproject',
            name='modified',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Modificado'),
        ),
        migrations.AlterField(
            model_name='finalproject',
            name='progress',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Avance del proyecto'),
        ),
        migrations.AlterField(
            model_name='finalproject',
            name='variation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Variacion'),
        ),
    ]
