# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-08-31 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_auto_20200821_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalproject',
            name='error_cell',
            field=models.TextField(blank=True, null=True, verbose_name='pila de errores'),
        ),
        migrations.AddField(
            model_name='finalproject',
            name='inserted_data',
            field=models.BooleanField(default=False, verbose_name='Datos insertados desde cuenta p\xfablica'),
        ),
        migrations.AddField(
            model_name='finalproject',
            name='json_variables',
            field=models.TextField(blank=True, null=True, verbose_name='Variables originales de su columna'),
        ),
        migrations.AddField(
            model_name='finalproject',
            name='name_in_pa',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Nombre como aparece en cuenta p\xfablica'),
        ),
        migrations.AddField(
            model_name='finalproject',
            name='similar_suburb_name',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True, verbose_name='Nivel de similitud de nombre (-1 cuando es forzado)'),
        ),
    ]
