# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-11 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20201113_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalproject',
            name='variation_calc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
