# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-11 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_finalproject_variation_calc'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalproject',
            name='range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
