# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-18 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_finalproject_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalproject',
            name='data_raw',
            field=models.TextField(blank=True, null=True, verbose_name='Informacion de la imagen'),
        ),
    ]
