# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2021-02-22 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_finalproject_data_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='votes_int',
            field=models.IntegerField(default=0, verbose_name='Votos internet'),
        ),
        migrations.AddField(
            model_name='project',
            name='votes_mro',
            field=models.IntegerField(default=0, verbose_name='Votos f\xedsicos'),
        ),
    ]
