# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-18 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_auto_20210222_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalproject',
            name='variation',
            field=models.FloatField(blank=True, null=True, verbose_name='Variacion'),
        ),
    ]
