# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-18 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_auto_20210518_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalproject',
            name='validated',
            field=models.NullBooleanField(verbose_name='Validado'),
        ),
    ]
