# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-19 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_auto_20210518_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalproject',
            name='progress',
            field=models.FloatField(blank=True, null=True, verbose_name='Avance del proyecto'),
        ),
    ]
