# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-21 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_auto_20210519_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anomalyfinalproject',
            name='public_account',
        ),
        migrations.AlterField(
            model_name='finalproject',
            name='image',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
