# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-24 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_col', models.CharField(max_length=8, verbose_name='Clave de la Colonia')),
                ('name', models.CharField(max_length=140, verbose_name='Nombre')),
                ('short_name', models.CharField(blank=True, max_length=140, null=True, verbose_name='Nombre  Corto')),
                ('compact_name', models.CharField(blank=True, max_length=140, null=True, verbose_name='Nombre alternativo seguro')),
                ('is_pilot', models.BooleanField(default=False, verbose_name='\xbfEs Piloto?')),
                ('start_year', models.IntegerField(default=2010, verbose_name='A\xf1o de inicio')),
                ('end_year', models.IntegerField(blank=True, null=True, verbose_name='A\xf1o de Fin')),
                ('pob_2010', models.IntegerField(blank=True, null=True, verbose_name='Poblacion en 2010')),
                ('pob_2015', models.IntegerField(blank=True, null=True, verbose_name='Poblacion en 2015')),
                ('pob_2020', models.IntegerField(blank=True, null=True, verbose_name='Poblacion en 2020')),
                ('secc_com', models.TextField(blank=True, null=True, verbose_name='Seccion Completa')),
                ('secc_parc', models.TextField(blank=True, null=True, verbose_name='Seccion Parcial')),
                ('derivation_suburb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens_suburb', to='geographic.Suburb', verbose_name='Colonia derivada de ')),
            ],
            options={
                'verbose_name': 'Colonia',
                'verbose_name_plural': 'Colonias',
            },
        ),
        migrations.CreateModel(
            name='SuburbGeoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_point', models.CharField(max_length=40, verbose_name='geo point')),
                ('geo_shape', models.TextField(verbose_name='geo shape')),
                ('geo_topo', models.TextField(verbose_name='geo topo')),
                ('suburb', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='geographic.Suburb', verbose_name='Colonia')),
            ],
        ),
        migrations.CreateModel(
            name='SuburbType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('abrev', models.CharField(blank=True, max_length=40, null=True, verbose_name='Abreviatura')),
                ('icon', models.CharField(blank=True, max_length=30, null=True, verbose_name='Icon')),
                ('emoji', models.CharField(blank=True, max_length=6, null=True, verbose_name='Emoji')),
            ],
            options={
                'verbose_name': 'Tipo de Colonia/Asentamiento',
                'verbose_name_plural': 'Tipos de Colonia/Asentamiento',
            },
        ),
        migrations.CreateModel(
            name='TownHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_inegi', models.CharField(max_length=6, verbose_name='Clave INEGI')),
                ('cve_alc', models.IntegerField(verbose_name='Clave de la Alcaldia')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('short_name', models.CharField(blank=True, max_length=12, null=True, verbose_name='Nombre Corto')),
                ('image', models.ImageField(blank=True, null=True, upload_to='townhall', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Alcald\xeda',
                'verbose_name_plural': 'Alcald\xedas',
            },
        ),
        migrations.CreateModel(
            name='TownHallGeoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_point', models.TextField(verbose_name='geo point')),
                ('geo_shape', models.TextField(verbose_name='geo shape')),
                ('townhall', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='geographic.TownHall', verbose_name='Alcaldia')),
            ],
        ),
        migrations.AddField(
            model_name='suburb',
            name='suburb_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geographic.SuburbType', verbose_name='Tipo de colonia'),
        ),
        migrations.AddField(
            model_name='suburb',
            name='townhall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geographic.TownHall', verbose_name='Alcald\xeda'),
        ),
    ]
