# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-07-13 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TownHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_inegi', models.CharField(max_length=6, verbose_name='Clave INEGI')),
                ('cve_alc', models.IntegerField(verbose_name='Clave de la Alcaldia')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('short_name', models.CharField(max_length=12, verbose_name='Nombre Corto')),
                ('image', models.ImageField(upload_to='townhall', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Alcaldia',
                'verbose_name_plural': 'Alcaldias',
            },
        ),
    ]
