# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-07-13 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geographic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suburb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_col', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=140)),
                ('short_name', models.CharField(blank=True, max_length=140, null=True)),
                ('is_pilot', models.BooleanField(default=False)),
                ('start_year', models.IntegerField(default=2010)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('pob_2010', models.IntegerField(blank=True, null=True)),
                ('pob_2015', models.IntegerField(blank=True, null=True)),
                ('pob_2020', models.IntegerField(blank=True, null=True)),
                ('secc_com', models.TextField(blank=True, null=True, verbose_name='Seccion Completa')),
                ('secc_parc', models.TextField(blank=True, null=True, verbose_name='Seccion Parcial')),
                ('derivation_suburb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens_suburb', to='geographic.Suburb')),
            ],
            options={
                'verbose_name': 'Colonia',
                'verbose_name_plural': 'Colonias',
            },
        ),
        migrations.CreateModel(
            name='SuburbGeoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_point', models.CharField(max_length=40)),
                ('geo_shape', models.TextField()),
                ('geo_topo', models.TextField()),
                ('suburb', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='geographic.Suburb')),
            ],
        ),
        migrations.CreateModel(
            name='SuburbType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('abrev', models.CharField(blank=True, max_length=40, null=True)),
                ('icon', models.CharField(blank=True, max_length=30, null=True)),
                ('emoji', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Colonia/Asentamiento',
                'verbose_name_plural': 'Tipos de Colonia/Asentamiento',
            },
        ),
        migrations.CreateModel(
            name='TownHallGeoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_point', models.TextField()),
                ('geo_shape', models.TextField()),
                ('townhall', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='geographic.TownHall')),
            ],
        ),
        migrations.AddField(
            model_name='suburb',
            name='sururb_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geographic.SuburbType'),
        ),
        migrations.AddField(
            model_name='suburb',
            name='townhall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geographic.TownHall', verbose_name='Alcaldia'),
        ),
    ]
