# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-07-14 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geographic', '0002_auto_20200713_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suburb',
            name='cve_col',
            field=models.CharField(max_length=8, verbose_name='Clave de la Colonia'),
        ),
        migrations.AlterField(
            model_name='suburb',
            name='derivation_suburb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens_suburb', to='geographic.Suburb', verbose_name='Colonia derivada de '),
        ),
        migrations.AlterField(
            model_name='suburb',
            name='end_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='A\xf1o de Fin'),
        ),
        migrations.AlterField(
            model_name='suburb',
            name='is_pilot',
            field=models.BooleanField(default=False, verbose_name='\xbfEs Piloto?'),
        ),
        migrations.AlterField(
            model_name='suburb',
            name='name',
            field=models.CharField(max_length=140, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='suburb',
            name='pob_2010',
            field=models.IntegerField(blank=True, null=True, verbose_name='Poblacion en 2010'),
        ),
        migrations.AlterField(
            model_name='suburb',
            name='pob_2015',
            field=models.IntegerField(blank=True, null=True, verbose_name='Poblacion en 2015'),
        ),
        migrations.AlterField(
            model_name='suburb',
            name='pob_2020',
            field=models.IntegerField(blank=True, null=True, verbose_name='Poblacion en 2020'),
        ),
        migrations.AlterField(
            model_name='suburb',
            name='short_name',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Nombre  Corto'),
        ),
        migrations.AlterField(
            model_name='suburb',
            name='start_year',
            field=models.IntegerField(default=2010, verbose_name='A\xf1o de inicio'),
        ),
        migrations.AlterField(
            model_name='suburb',
            name='sururb_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geographic.SuburbType', verbose_name='Tipo de colonia'),
        ),
        migrations.AlterField(
            model_name='suburbgeodata',
            name='geo_point',
            field=models.CharField(max_length=40, verbose_name='geo point'),
        ),
        migrations.AlterField(
            model_name='suburbgeodata',
            name='geo_shape',
            field=models.TextField(verbose_name='geo shape'),
        ),
        migrations.AlterField(
            model_name='suburbgeodata',
            name='geo_topo',
            field=models.TextField(verbose_name='geo topo'),
        ),
        migrations.AlterField(
            model_name='suburbgeodata',
            name='suburb',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='geographic.Suburb', verbose_name='Colonia'),
        ),
        migrations.AlterField(
            model_name='suburbtype',
            name='abrev',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Abreviatura'),
        ),
        migrations.AlterField(
            model_name='suburbtype',
            name='emoji',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Emoji'),
        ),
        migrations.AlterField(
            model_name='suburbtype',
            name='icon',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='suburbtype',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='townhallgeodata',
            name='geo_point',
            field=models.TextField(verbose_name='geo point'),
        ),
        migrations.AlterField(
            model_name='townhallgeodata',
            name='geo_shape',
            field=models.TextField(verbose_name='geo shape'),
        ),
        migrations.AlterField(
            model_name='townhallgeodata',
            name='townhall',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='geographic.TownHall', verbose_name='Alcaldia'),
        ),
    ]
