# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-07-14 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geographic', '0003_auto_20200714_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='townhall',
            options={'verbose_name': 'Alcald\xeda', 'verbose_name_plural': 'Alcald\xedas'},
        ),
        migrations.AlterField(
            model_name='suburb',
            name='sururb_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geographic.SuburbType', verbose_name='Tipo de colonia'),
        ),
        migrations.AlterField(
            model_name='townhall',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='townhall', verbose_name='Imagen'),
        ),
    ]
