# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-07-14 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geographic', '0004_auto_20200714_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='townhall',
            name='short_name',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Nombre Corto'),
        ),
    ]
