# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-07-27 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geographic', '0005_auto_20200714_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suburb',
            old_name='sururb_type',
            new_name='suburb_type',
        ),
    ]
