# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-08-14 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geographic', '0006_auto_20200727_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='suburb',
            name='compact_name',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Nombre sin espacios ni caracteres'),
        ),
        migrations.AlterField(
            model_name='suburb',
            name='townhall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geographic.TownHall', verbose_name='Alcald\xeda'),
        ),
    ]
