# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-08-22 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geographic', '0007_auto_20200814_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suburb',
            name='compact_name',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Nombre alternativo seguro'),
        ),
    ]
